import { Experience } from "../interfaces/experience.interface";
import scalex from "../assets/images/scalex.png";
import mphasis from "../assets/images/mphasis.png";
import evaeco from "../assets/images/evaeco.jpeg";

export const experiences: Experience[] = [
  {
    title: "Full Stack Developer Intern",
    company: "Eva Eco System Inc.",
    duration: "Feb. 2025 – April 2025",
    location: "Houston, TX, USA",
    responsibilities: [
      "Developed a React Native valet-driver app featuring GPS tracking via Google Maps and Mapbox, secure authentication with Apple Login and Google OAuth and stripe payment integration.",
    ],
    image: evaeco,
    skills: [
      "React Native",
      "GPS & Location Services",
      "Google Maps API",
      "Mapbox",
      "Authentication",
      "Apple Login",
      "Google OAuth",
      "Stripe",
      "Payment Integration",
    ],
  },
  {
    title: "Software Engineer 3",
    company: "Scalex Technology Solutions LLP",
    duration: "Nov. 2020 – Dec. 2023",
    location: "Pune, MH, India",
    responsibilities: [
      "Led a team of 6 in building scalable microservices with Node.js, Express.js, TypeScript and MongoDB.",
      "Architected a high-performance micro-frontend for a React.js application using Ant Design and Redux, achieving a 40% faster load time.",
      "Took end-to-end ownership of integrating Stripe and PayPal payment processing and implementing a secure authentication and notification system leveraging Amazon Cognito, SNS, and SES.",
    ],
    image: scalex,
    skills: [
      "Node.js",
      "Express.js",
      "TypeScript",
      "REST APIs",
      "MongoDB",
      "React.js",
      "Ant Design",
      "Redux",
      "Stripe",
      "PayPal",
      "Amazon Cognito",
      "OAuth2.0",
      "Amazon SNS",
      "Amazon SES",
      "Socket.IO",
      "ElasticSearch",
      "Webpack",
      "GitHub Actions",
      "React Native",
      "Twilio SDK",
      "Firebase",
      "CleverTap",
      "Jest",
      "SCSS",
      "React Data Table Component",
      "Liberty Mutual API",
      "Chubb API",
    ],
  },
  {
    title: "Associate Software Engineer",
    company: "Mphasis Ltd.",
    duration: "Sep. 2019 – Feb. 2020",
    location: "Pune, MH, India",
    responsibilities: [
      "Developed a Java Spring Boot BFF microservice with RESTful APIs, versioning, and security, optimizing Oracle SQL queries and achieving 90% test coverage with JUnit and Mockito, while also integrating JSP and Servlets for dynamic web pages. This resulted in a 75% reduction in redundant queries, a 30% improvement in data delivery speed, and a 25% decrease in bugs.",
    ],
    image: mphasis,
    skills: [
      "Java",
      "Spring Boot",
      "BFF (Backend For Frontend)",
      "Microservices",
      "RESTful APIs",
      "SQL",
      "Oracle",
      "JUnit",
      "Mockito",
      "JSP",
      "Servlets",
    ],
  },
];
